TEAM_ALIASES = {
    "afc wimbledon": "AFC Wimbledon",
    "wimbledon": "AFC Wimbledon",
    "alkmaar": "AZ Alkmaar",
    "az": "AZ Alkmaar",
    "az alkmaar": "AZ Alkmaar",
    "adana demirspor": "Ad. Demirspor",
    "ad demirspor": "Ad. Demirspor",
    "demirspor": "Ad. Demirspor",
    "athletic bilbao": "Ath Bilbao",
    "ath bilbao": "Ath Bilbao",
    "bilbao": "Ath Bilbao",
    "atletico madrid": "Ath Madrid",
    "atl madrid": "Ath Madrid",
    "ath madrid": "Ath Madrid",
    "atleti": "Ath Madrid",
    "beerschot": "Beerschot VA",
    "beerschot va": "Beerschot VA",
    "ado den haag": "Den Haag",
    "den haag": "Den Haag",
    "eintracht frankfurt": "Ein Frankfurt",
    "ein frankfurt": "Ein Frankfurt",
    "frankfurt": "Ein Frankfurt",
    "bb erzurumspor": "Erzurum BB",
    "erzurum bb": "Erzurum BB",
    "erzurumspor": "Erzurum BB",
    "emmen": "FC Emmen",
    "fc emmen": "FC Emmen",
    "cologne": "FC Koln",
    "fc koln": "FC Koln",
    "fc köln": "FC Koln",
    "koln": "FC Koln",
    "köln": "FC Koln",
    "fortuna sittard": "For Sittard",
    "for sittard": "For Sittard",
    "gil vicente": "Gil Vicente",
    "go ahead": "Go Ahead Eagles",
    "go ahead eagles": "Go Ahead Eagles",
    "deportivo la coruna": "La Coruna",
    "deportivo la coruña": "La Coruna",
    "la coruna": "La Coruna",
    "la coruña": "La Coruna",
    "las palmas": "Las Palmas",
    "le havre": "Le Havre",
    "le mans": "Le Mans",
    "manchester city": "Man City",
    "man city": "Man City",
    "mancity": "Man City",
    "mcfc": "Man City",
    "manchester united": "Man United",
    "man united": "Man United",
    "man utd": "Man United",
    "man utd.": "Man United",
    "manutd": "Man United",
    "mufc": "Man United",
    "nac": "NAC Breda",
    "nac breda": "NAC Breda",
    "psg": "Paris SG",
    "paris saint germain": "Paris SG",
    "paris saint-germain": "Paris SG",
    "paris sg": "Paris SG",
    "paris fc": "Paris FC",
    "pau": "Pau FC",
    "pau fc": "Pau FC",
    "raal la louviere": "RAAL La Louviere",
    "raal la louvière": "RAAL La Louviere",
    "rb leipzig": "RB Leipzig",
    "red bull leipzig": "RB Leipzig",
    "leipzig": "RB Leipzig",
    "rwd molenbeek": "RWD Molenbeek",
    "molenbeek": "RWD Molenbeek",
    "red star": "Red Star",
    "rio ave": "Rio Ave",
    "schalke": "Schalke 04",
    "schalke 04": "Schalke 04",
    "real sociedad b": "Sociedad B",
    "sociedad b": "Sociedad B",
    "sporting braga": "Sp Braga",
    "sp braga": "Sp Braga",
    "braga": "Sp Braga",
    "sporting gijon": "Sp Gijon",
    "sporting gijón": "Sp Gijon",
    "sp gijon": "Sp Gijon",
    "sp gijón": "Sp Gijon",
    "sporting lisbon": "Sp Lisbon",
    "sporting cp": "Sp Lisbon",
    "sporting clube de portugal": "Sp Lisbon",
    "sporting": "Sp Lisbon",
    "sp lisbon": "Sp Lisbon",
    "saint etienne": "St Etienne",
    "saint-etienne": "St Etienne",
    "st etienne": "St Etienne",
    "st. etienne": "St Etienne",
    "saint pauli": "St Pauli",
    "st pauli": "St Pauli",
    "st. pauli": "St Pauli",
    "sankt pauli": "St Pauli",
    "sint truiden": "St Truiden",
    "st truiden": "St Truiden",
    "st. truiden": "St Truiden",
    "union saint gilloise": "St. Gilloise",
    "union saint-gilloise": "St. Gilloise",
    "saint gilloise": "St. Gilloise",
    "st gilloise": "St. Gilloise",
    "st. gilloise": "St. Gilloise",
    "vvv": "VVV Venlo",
    "vvv venlo": "VVV Venlo",
    "venlo": "VVV Venlo",
    "villarreal b": "Villarreal B",
    "willem ii": "Willem II",
    "willem 2": "Willem II",
}


def normalize_team_name(value):
    return " ".join(str(value).lower().replace(".", " ").split())


def canonical_team_name(value, known_teams=None):
    cleaned = str(value).strip()
    key = normalize_team_name(cleaned)

    if key in TEAM_ALIASES:
        return TEAM_ALIASES[key]

    if known_teams:
        lower_map = {normalize_team_name(team): team for team in known_teams}
        if key in lower_map:
            return lower_map[key]

    return cleaned
